name: rastreamento_app_admin
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.12.2
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0
  socket_io_client: ^3.1.2
  collection: ^1.19.1
  logging: ^1.3.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
